version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alan
      MYSQL_USER: root
      MYSQL_PASSWORD: 
  