version: "3.8"

services:

  db:
    #network_mode: host
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=v6vpxdkd
      - POSTGRES_DB=alanturing
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - fullstack

  go:
    #network_mode: host
    build: .
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=v6vpxdkd
      - DB_DB=alanturing
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    networks:
      - fullstack

volumes:
  dbdata:

networks:
  fullstack:
    driver: bridge
