version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v6vpxdkd
      # Optional: Give a name to the database, otherwise
      # use the default value POSTGRES_USER as a database name (user in this case.)
      POSTGRES_DB: alanturing
    ports:
      - "5432:5432"
    networks:
      - mynet

  go:
    container_name: go
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
