version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v6vpxdkd
      POSTGRES_DB: turingdb
    ports:
      - "5432:5432"
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  go:
    build: .
    container_name: "go"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "v6vpxdkd"
      DB_DB: "turingdb"
      DB_TABLE: "turingdb"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "3000:8080"
    depends_on:
      - "postgres"
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
